// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAPIVideoIDOKCode is the HTTP code returned for type GetAPIVideoIDOK
const GetAPIVideoIDOKCode int = 200

/*GetAPIVideoIDOK Successful response

swagger:response getApiVideoIdOK
*/
type GetAPIVideoIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetAPIVideoIDOKBody `json:"body,omitempty"`
}

// NewGetAPIVideoIDOK creates GetAPIVideoIDOK with default headers values
func NewGetAPIVideoIDOK() *GetAPIVideoIDOK {

	return &GetAPIVideoIDOK{}
}

// WithPayload adds the payload to the get Api video Id o k response
func (o *GetAPIVideoIDOK) WithPayload(payload *GetAPIVideoIDOKBody) *GetAPIVideoIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api video Id o k response
func (o *GetAPIVideoIDOK) SetPayload(payload *GetAPIVideoIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIVideoIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
